name: Discipline - The Key to Success

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "lll0425"
          git config --global user.email "willy791124@gmail.com"

      - name: Create or Update Daily Log
        run:
           |
          export TZ="Asia/Taipei"
          mkdir -p $GITHUB_WORKSPACE/daily
          FILENAME="$GITHUB_WORKSPACE/daily/$(date +'%Y-%m-%d').md"
          echo "# 日期: $(date +'%Y-%m-%d')" > $FILENAME
          echo "## 今日任務:" >> $FILENAME
          echo "- [ ] 任務 1:區塊練筆記上課就結束" >> $FILENAME
          echo "  > 註解:" >> $FILENAME
          echo "- [ ] 任務 2:找出MIA現在的進展 問gpt如何延伸" >> $FILENAME
          echo "  > 註解:" >> $FILENAME
          echo "- [ ] 任務 3:刷題" >> $FILENAME
          echo "  > 註解:" >> $FILENAME
          echo "更新時間: $(date '+%H:%M:%S')" >> $FILENAME

      - name: Pull latest changes
        run: |
          git pull origin main --allow-unrelated-histories

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "2025-02-25 Daily Log"
          git push https://github.com/lll0425/daily.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
